plugins {
    id 'com.android.application' version '9.2.0'
}

android {
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.5.0'
    }
    namespace 'com.meras.userapp'
    compileSdk 34

    defaultConfig {
        applicationId 'com.meras.userapp'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}